-- MySQL Script generated by MySQL Workbench
-- Wed Jul 15 21:04:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notaria` DEFAULT CHARACTER SET utf8 ;
USE `notaria` ;

-- -----------------------------------------------------
-- Table `notaria`.`poderes_bancarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notaria`.`poderes_bancarios` ;

CREATE TABLE IF NOT EXISTS `notaria`.`poderes_bancarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rut_emisor` INT(11) NOT NULL,
  `nombre_emisor` VARCHAR(100) NOT NULL,
  `apellido_paterno_emisor` VARCHAR(100) NOT NULL,
  `apellido_materno_emisor` VARCHAR(100) NOT NULL,
  `direccion_emisor` VARCHAR(100) NOT NULL,
  `comuna_emisor` VARCHAR(100) NOT NULL,
  `nombre_receptor` VARCHAR(100) NOT NULL,
  `apellido_paterno_receptor` VARCHAR(100) NOT NULL,
  `apellido_materno_receptor` VARCHAR(100) NOT NULL,
  `rut_receptor` INT(11) NOT NULL,
  `banco` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT 'pendiente',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notaria`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notaria`.`user` ;

CREATE TABLE IF NOT EXISTS `notaria`.`user` (
  `rut` INT(11) NOT NULL,
  `names` VARCHAR(255) NOT NULL,
  `paternal_last_name` VARCHAR(100) NOT NULL,
  `maternal_last_name` VARCHAR(100) NOT NULL,
  `telefono` INT(11) NOT NULL,
  `address` TEXT NOT NULL,
  `comuna` VARCHAR(50) NOT NULL,
  `ciudad` VARCHAR(50) NOT NULL,
  `sexo` BINARY(1) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
