-- MySQL Script generated by MySQL Workbench
-- Sat Jun 13 19:25:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notaria` DEFAULT CHARACTER SET utf8 ;
USE `notaria` ;

-- -----------------------------------------------------
-- Table `notaria`.`poderes_bancarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notaria`.`poderes_bancarios` ;

CREATE TABLE IF NOT EXISTS `notaria`.`poderes_bancarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rut_emisor` INT NOT NULL,
  `nombre_emisor` VARCHAR(100) NOT NULL,
  `apellido_paterno_emisor` VARCHAR(100) NOT NULL,
  `apellido_materno_emisor` VARCHAR(100) NOT NULL,
  `direccion_emisor` VARCHAR(100) NOT NULL,
  `comuna_emisor` VARCHAR(100) NOT NULL,
  `nombre_receptor` VARCHAR(100) NOT NULL,
  `apellido_paterno_receptor` VARCHAR(100) NOT NULL,
  `apellido_materno_receptor` VARCHAR(100) NOT NULL,
  `rut_receptor` INT NOT NULL,
  `banco` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notaria`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notaria`.`user` ;

CREATE TABLE IF NOT EXISTS `notaria`.`user` (
  `rut` INT NOT NULL COMMENT 'identificador del usuario, numero de identidad unico',
  `names` VARCHAR(255) NOT NULL COMMENT 'nombres del usuario\n',
  `paternal_last_name` VARCHAR(255) NOT NULL COMMENT 'apellido paterno del usuario',
  `maternal_last_name` VARCHAR(255) NOT NULL COMMENT 'apellido materno del usuario',
  `telefono` INT NOT NULL COMMENT 'numero telefonico de contacto del usuario',
  `address` TEXT NOT NULL COMMENT 'domicilio del usuario',
  `comuna` VARCHAR(50) NOT NULL COMMENT 'comuna del usuario',
  `ciudad` VARCHAR(50) NOT NULL COMMENT 'ciudad del usuario',
  `sexo` BINARY(1) NOT NULL COMMENT 'sexo del usuario',
  `email` VARCHAR(80) NOT NULL COMMENT 'email del usuario',
  `password` VARCHAR(255) NOT NULL COMMENT 'contraseña del usuario',
  PRIMARY KEY (`rut`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
